# SPDX-License-Identifier: CC0-1.0
#
# Copyright (C) 2019 CERN

ifdef CONFIG_SUPER_REPO
ifdef CONFIG_SUPER_REPO_VERSION
SUBMODULE_VERSIONS-y += MODULE_INFO(version_$(CONFIG_SUPER_REPO),\"$(CONFIG_SUPER_REPO_VERSION)\");
endif
endif

ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"
ccflags-y += -Werror
ccflags-y += -I$(src)/../../../include

# priority to our local headers (avoid conflict with the version in kernel)
LINUXINCLUDE := -I$(src)/../../../include $(LINUXINCLUDE)
LINUXINCLUDE := -I$(src)/../../../include/linux $(LINUXINCLUDE)

obj-$(CONFIG_I2C_OCORES) += i2c-ocores.o