files = [	"gencores_pkg.vhd",
                "gc_crc_gen.vhd",
                "gc_moving_average.vhd",
                "gc_extend_pulse.vhd",
                "gc_delay_gen.vhd",
                "gc_dual_pi_controller.vhd",
                "gc_serial_dac.vhd",
                "gc_sync_ffs.vhd",
                "gc_arbitrated_mux.vhd",
                "gc_pulse_synchronizer.vhd",
                "gc_frequency_meter.vhd",
                "gc_dual_clock_ram.vhd",
                "gc_wfifo.vhd"];
