# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2019 CERN

ifdef CONFIG_SUPER_REPO
ifdef CONFIG_SUPER_REPO_VERSION
SUBMODULE_VERSIONS-y += MODULE_INFO(version_$(CONFIG_SUPER_REPO),\"$(CONFIG_SUPER_REPO_VERSION)\");
endif
endif

ccflags-y += -I$(src)/../../include

obj-$(CONFIG_SPI_OCORES) += spi-ocores.o