files = ["cordic_init.vhd",
         "cordic_modulo_360.vhd",
         "cordic_xy_logic_hd.vhd",
         "cordic_xy_logic_nhd.vhd",
         "cordic_xy_logic_nmhd.vhd",
         "gc_pipelined_fir_filter.vhd",
         "gc_cordic_pkg.vhd",
         "gc_cordic.vhd",
         "gc_cordic_top.vhd",
         "gc_dsp_pkg.vhd",
         "gc_iq_demodulator.vhd",
         "gc_iq_modulator.vhd",
         "gc_pi_regulator.vhd",
         "gc_soft_ramp_switch.vhd",
         "gc_integer_divide.vhd"];
